apiVersion: apps/v1
kind: Deployment
metadata:
    name: calsoft-deployment
    namespace: demo
spec:
    replicas: 10
    selector:
        matchLabels:
            env: test
    template:
        metadata:
            labels:
                env: test
        spec:
            containers:
                - name: calsoft
                  image: shubh9975/simple-app:v3
