pipeline {
    agent any	
    /*environment {
        //GITHUB_TOKEN = credentials('afdcc8c7-083e-4836-b577-3a24ceaca338')
	//GITHUB_TOKEN = credentials('')    
    }*/
    options {
        buildDiscarder(logRotator(artifactDaysToKeepStr: '30', artifactNumToKeepStr: '5', daysToKeepStr: '30', numToKeepStr: '5'))
        timestamps()
    }
    tools {
        maven 'maven-3.8.5-auto'
    }
    stages {
	 stage('checkoutcodes') {
           steps {
         
             git credentialsId: '9ba1a1b8-a293-492e-857e-0afa2f21d997', branch: "master", url: 'https://github.com/rameshmasagani/personal-projects.git'
           }
         }
    
         stage('build to maven') {
           steps {
             sh "mvn clean package"
           }
         }
         
	 stage('Execute sonarqube reports') {
           steps {
	     sh "mvn sonar:sonar"
	   }
	 }
	    
         stage('docker image to BUILD ') {
           steps {
             sh "docker build -t prasadve0506/personal-projects:${BUILD_NUMBER} ."
           }
	 }
          stage('docker login and push') {
            steps {
              withCredentials([string(credentialsId: 'DockerHubPwd', variable: 'DockerHubPwd')]) {
                sh "docker login -u prasadve0506 -p ${DockerHubPwd}"
		sh "docker push  prasadve0506/personal-projects:${BUILD_NUMBER}"
              }
            
            }
          }
    }
    post {
        always{
            //cleanWorkspace()
	    print "hi"	
        }
        success {
            emailext attachLog: true,
                body: 'Pipeline job ${JOB_NAME} success. Build URL: ${BUILD_URL}',
                recipientProviders: [[$class: 'CulpritsRecipientProvider']],
                subject: 'SUCCESS: Jenkins Job- ${JOB_NAME} Build No- ${BUILD_NUMBER}',
                to: 'nilesh.arte@calsoftinc.com'
        }
        failure {
            emailext attachLog: true,
                body: 'Pipeline job ${JOB_NAME} failed. Build URL: ${BUILD_URL}',
                recipientProviders: [[$class: 'CulpritsRecipientProvider'], [$class: 'DevelopersRecipientProvider'], [$class: 'FailingTestSuspectsRecipientProvider'], [$class: 'UpstreamComitterRecipientProvider']],
                subject: 'FAILED: Jenkins Job- ${JOB_NAME} Build No- ${BUILD_NUMBER}',
                to: 'nilesh.arte@calsoftinc.com'
        }
    }
}
